language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - build-tools-26.0.2
    - build-tools-28.0.0
    - android-26
    - android-28
    - extra
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
    - addon-google_apis-google-28
    
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-28

script:
 - ./gradlew build connectedCheck
before_install:
- chmod +x gradlew
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;28.0.3"
# Create and start emulator.
- echo no | android create avd --force -n test -t "android-26" --abi "armeabi-v7a" --tag "google_apis"
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'


cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
