language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-28.0.0
    - android-28
    - extra
script:
 - ./gradlew build connectedCheck
before_install:
- chmod +x gradlew
- yes | sdkmanager "platforms;android-28"
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
